# Generated by Django 4.1.1 on 2022-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_alter_diary_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='case_Date',
            field=models.DateField(),
        ),
    ]
